### ISSUE TITLE
ld: library not found for -lomp

### ISSUE THREAD

**Issue by stefanfritsch** [r-lib/ps#109]
Hi,

as has been reported a number of times (#56, #81, #108), `ps` has issues if you use a non-standard compiler on OSX:
```
 installing *source* package ‘ps’ ...
** package ‘ps’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
/opt/homebrew/opt/llvm/bin/clang -fopenmp -g -O3 -Wall -pedantic -std=gnu99 -mtune=native -pipe -Wall px.c -o px
ld: library not found for -lomp
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [px] Error 1
ERROR: compilation failed for package ‘ps’
* removing ‘/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/ps’
Error in i.p(...) : 
  (converted from warning) installation of package ‘ps’ had non-zero exit status
```

The problem is that you don't add the linker flags in [src/Makevars.in]:

What it looks like:
```
px: px.c
	$(CC) $(CFLAGS) -Wall px.c -o px 

interrupt: interrupt.c
	$(CC) $(CFLAGS) -Wall interrupt.c -o interrupt
```

The fix:
<pre>
px: px.c
	$(CC) $(CFLAGS) -Wall px.c -o px <b>$(LDFLAGS)</b>

interrupt: interrupt.c
	$(CC) $(CFLAGS) -Wall interrupt.c -o interrupt <b>$(LDFLAGS)</b>
</pre>

Note: I'm anything but a C crack, you probably should ask someone with a deeper understanding of `Makefile` syntax whether there are any unintended side-effects. But it works for me&trade;

Best regards,
Stefan

**Comment by gaborcsardi** [comment]
Thanks! I can't reproduce the failure, so I can't check it. But let's add it and we'll see. Do you want to submit a PR?

**Comment by gaborcsardi** [comment]
I could finally reproduce this with the instructions freom https://github.com/Rdatatable/data.table/wiki/Installation#openmp-enabled-compiler-for-mac
