### ISSUE TITLE
 ps/man/ps_loadavg.Rd is "broken"

### ISSUE THREAD

**Issue by gwd999** [r-lib/ps#112]
@gaborcsardi 
Please [potentially] have a look at `ps/man/ps_loadavg.Rd` here in the repo 
The `title == description` which causes problems on some builds from source - strangely it only happened / I noticed it only (threw weird errors) when building in R-4.0.4 on WIN 10  **cygwin** 

Since it looks like you are using some extra packages ("roxygenlabs") to build the .Rd files, there could be some flaws in that extra package or just in your `ps_loadavg` roxygen comments - did not investigate in detail, just fixed the `ps_loadavg.Rd` by hand on my side and build worked w/o errors again. 

thought I'd let you know ...

**Comment by gaborcsardi** [comment]
> The title == description which causes problems on some builds from source

What problems exactly?

**Comment by gaborcsardi** [comment]
> am I guessing right that the ps pkg is not functional under cygwin R

I don't know, what do `ps::ps_os_type()`, `.Platform$OS.type` and `R.version$platform` return?

**Comment by gwd999** [comment]
> I don't know, what do `ps::ps_os_type()`, `.Platform$OS.type` and `R.version$platform` return?

when starting R ... 
```
Error: Not implemented on this platform: `ps_handle`
> ps::ps_os_type()
  POSIX WINDOWS   LINUX   MACOS
  FALSE   FALSE   FALSE   FALSE
Error : Not implemented on this platform: `ps_handle`
```

```
> .Platform$OS.type
[1] "unix"
Error : Not implemented on this platform: `ps_handle`
```

which made me expect that `ps` would work w/o any issues
but probably those `.c`  files you have in the package dig deeper 

```
> R.version$platform
[1] "x86_64-pc-cygwin"
Error : Not implemented on this platform: `ps_handle`
``` 
I left the `Error : Not implemented on this platform: 'ps_handle'` message in there - but you can ignore that  ... is a result of my startup process including a package that depends on `ps` indirectly

**Comment by gwd999** [comment]
Of course - no big deal ... I am using it anyway mainly on WIN10 and WSL2 Ubuntu 
It was more of a "geek weekend project" that had me run into this and curiosity on th etopic that made me reach out. 
A small positive(?) side-effect was just that I noticed the "exotic" title length in the documentation - so it at least had a little QA (quality assurance) benefit to it, as well as maybe some informative value in case someone else runs into it some future date. 
PS: by the way -> your prompt package (the git prompt functionality) really rocks! of course the other ones are also awesome - guess [prompt] is just "in my face" every day so that's why it comes to my mind first ... have a nice rest of weekend
