### ISSUE TITLE
Support other OSes?

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/ps#13]
- [ ] FreeBSD?
- [ ] NetBSD?
- [ ] OpenBSD?
- [ ] AIX?

**Comment by rhurlin** [comment]
Hi @gaborcsardi ,
I Don't know, if this issue is the right one but hope so.

I try to install ps 1.7.0 on **FreeBSD** 14.0-CURRENT with R 4.2.0 and get the following error:

```
installing via 'install.libs.R' to /usr/home/rhurlin/R/library/00LOCK-ps/00new/ps
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘ps’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/home/rhurlin/R/library/00LOCK-ps/00new/ps/libs/ps.so':
  /usr/home/rhurlin/R/library/00LOCK-ps/00new/ps/libs/ps.so: Undefined symbol "psll_memory_uss"
Error: loading failed
Execution halted
ERROR: loading failed
```
Is there any chance to activate the FreeBSD specific code in ps?  Please let me know, if I should give more info or test something.

Many thanks in advance,
Rainer

**Comment by gaborcsardi** [comment]
There is no FreeBSD specific code in ps. The installation issue has been fixed already in this repo, but ps functions will not work on FreeBSD.

**Comment by gaborcsardi** [comment]
> Oops, what's the reason for ps not working on FreeBSD?
> With FreeBSD specific code I meant the commented-out lines in configure and src/api-common.c.

ps never had a FreeBSD implementetion.

**Comment by uzsolt** [comment]
Hi Gábor,
what about FreeBSD support?
See this PR: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=280006

**Comment by gaborcsardi** [comment]
PRs are welcome for freebsd. :)

**Comment by gaborcsardi** [comment]
Seems like this is not happening any time soon, so I am going to close it.
