### ISSUE TITLE
ps_system_memory()$percent is differently scaled on Windows and Linux

### ISSUE THREAD

**Issue by francisbarton** [r-lib/ps#131]
If I run `ps::ps_system_memory()` on Linux, I get a number between 0 and 100 returned for the `$percent` element, eg `82.02327`.
Running the same command on Windows, I get a number between 0 and 1 for `$percent`, eg `0.8202327`.

I think the output should be consistent - either way.
Or should it be up to the user to amend their script to account for which OS it is being run on?

**Comment by gaborcsardi** [comment]
You are right, this is not great. Would you like to submit a PR to fix the number on windows? (No pressure.)

**Comment by francisbarton** [comment]
Yes, happy to try. I'll have a look at the code soon.
