### ISSUE TITLE
ps_name error

### ISSUE THREAD

**Issue by flodel** [r-lib/ps#150]
---

Sorry it is difficult to give a reproducible example… I have encountered a situation where ps_name errors out as it evaluates 

`if(!is.null(cmdline))`

The issue is that `cmdline` is `character(0L)` at this point, so it dies evaluating `if(NA)`. Please consider changing the line to

`if(!is.null(cmdline)) && length(cmdline) > 0L)`

?

(I am using version 1.7.4 but see the same code in the current 1.7.5)

**Comment by gaborcsardi** [comment]
IDK how `ps_cmdline()` could return an empty vector, but yeah, we can defend against that. Do you want to submit a PR?

**Comment by flodel** [comment]
Yep, probably this weekend. Thanks.

**Comment by gaborcsardi** [comment]
Fixed in #152.
