### ISSUE TITLE
Install fails on arm64 Windows

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/ps#151]
The pdh.dll file is missing, apparently:
```
clang -shared -s -static-libgcc -o ps.dll tmp.def init.o api-common.o common.o extra.o dummy.o error-codes.o windows.o api-windows.o api-windows-conn.o arch/windows/process_info.o arch/windows/process_handles.o arch/windows/wmi.o -lpsapi -lkernel32 -ladvapi32 -lshell32 -lnetapi32 -liphlpapi -lwtsapi32 -lws2_32 -lPowrProf -lPdh -L. -LC:\rtools43\aarch64-w64-mingw32.static.posix/lib -LC:\rtools43\aarch64-w64-mingw32.static.posix/lib -LC:/PROGRA~1/R/R-devel/bin -lR
lld: error: unable to find library -lPdh
clang-17: error: linker command failed with exit code 1 (use -v to see invocation)
installing via 'install.libs.R' to C:/Users/gaborcsardi/AppData/Local/R/win-library/4.4/00LOCK-ps/00new/ps
```

If I copy `c:\windows\system32\pdh.dll` into `/src` then the install works, but `ps::ps_loadavg()`, which uses pdh, crashes. The crash remains even if I copy pdh.dll into the installed package.

**Comment by jeroen** [comment]
I see the same thing, the problem is that `libpdh.a` is missing from the mxe toolchain. This must be a bug because it is there for the msys2 toolchains (part of the mingw-w64 crt package): https://packages.msys2.org/package/mingw-w64-clang-aarch64-crt-git?repo=clangarm64

**Comment by gaborcsardi** [comment]
Yeah, they'll probably include it at some point, until then I can work around it some way.

**Comment by gaborcsardi** [comment]
I reported it here: https://bugs.r-project.org/show_bug.cgi?id=18606

**Comment by gaborcsardi** [comment]
Fixed now in Rtools43.
