### ISSUE TITLE
identifier "pid_t" is undefined while build ps in R 3.5.1 by using intel icc 2018.3

### ISSUE THREAD

**Issue by quanmqiu** [r-lib/ps#39]
env:
CentOS 6.10
R 3.5.1
Intel parallel studio 2018.3

command:
install.packages("ps")

error log:
installing *source* package ‘ps’ ...
** package ‘ps’ successfully unpacked and MD5 sums checked
** libs
icc -std=c99 -g -O3 -wd188 -ip -fp-model precise -qopt-mem-layout-trans=3 -xHost -mavx  -Wall px.c -o px
icc -I"/opt/CRAN/R-3.5.1/lib64/R/include" -DNDEBUG  -I/opt/extralib/bzip2-1.0.6 -I/opt/extralib/zlib-1.2.11/include -I/opt/extralib/xz-5.2.3/include -I/opt/extralib/pcre-8.42/include -I/opt/extralib/curl-7.59.0/include   -fpic  -std=c99 -g -O3 -wd188 -ip -fp-model precise -qopt-mem-layout-trans=3 -xHost -mavx  -c init.c -o init.o

In file included from init.c(4):
ps-internal.h(25): error: identifier "pid_t" is undefined
    pid_t pid;
    ^
compilation aborted for init.c (code 2)
make: *** [init.o] Error 2
ERROR: compilation failed for package ‘ps’
-
perhaps need this two header? 
#include <sys/types.h>
#include <unistd.h>

**Comment by gaborcsardi** [comment]
Thanks!  Have you tried it with the headers? I don't have icc, so can't try, but happy to add it if it helps.
