### ISSUE TITLE
is_os_supported(): check whether current platform is supported or not

### ISSUE THREAD

**Issue by HenrikBengtsson** [r-lib/ps#40]
The README reads:
> ps currently supports Windows (from Vista), macOS and Linux systems. On unsupported platforms the package can be installed and loaded, but **_all_ of its functions fail with an error of class "not_implemented"**.

Does that "all of its functions" means either all functions work or none at all?   If so, would it make sense to add a function for querying the support, e.g.

```r
if (ps::is_os_supported()) {
  processes <- ps::ps()
  ...
}
```
?

**Comment by gaborcsardi** [comment]
Are you looking for `ps::ps_is_supported()`?

**Comment by HenrikBengtsson** [comment]
> Yes, almost.  [...]
Thxs.

> Are you looking for ps::ps_is_supported()?

Doh. Not sure how I failed to find that one. It could bc I only browsed the topic index in the reference manual on CRAN which doesn't list it (the index at the end does - so do the HTML index).
