### ISSUE TITLE
library not found for -lomp

### ISSUE THREAD

**Issue by naarkhoo** [r-lib/ps#56]
my devtools installation fail with and error regarding `library not found for -lomp` this error occurs right after "`install.pacages("devtools")`"

```
** libs
/usr/local/opt/llvm/bin/clang -fopenmp -g -O3 -Wall -pedantic -std=gnu99 -mtune=native -pipe -Wall px.c -o px
ld: library not found for -lomp
clang-7: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [px] Error 1
ERROR: compilation failed for package ‘ps’
* removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/ps’

```

my settings, 

```
platform       x86_64-apple-darwin13.4.0   
arch           x86_64                      
os             darwin13.4.0                
system         x86_64, darwin13.4.0        
status                                     
major          3                           
minor          3.3                         
year           2017                        
month          03                          
day            06                          
svn rev        72310                       
language       R                           
version.string R version 3.3.3 (2017-03-06)
nickname       Another Canoe               
```

Originally I had the latest version of R, but I read some people could resolve by downgrading their R version. So in other words, I have the same problem with R3.5.1

**Comment by gaborcsardi** [comment]
ps does not use this library. Can you compile other packages with compiled code?
Also, I am not sure why your R installation uses the custom CRAN compiler. AFAIR R  3.3 was compiled with the Apple compilers. (But I am not sure.)

I suspect that this might be a bug in the custom CRAN compiler. Two ideas:
- install clang4 from here: http://r.research.att.com/libs/ You do not actually need to use it (!), just install it. There is a bug in the new CRAN clang compiler that makes it link to libraries from their old package.
- or, remove the CRAN compilers altogether, if you don't really need them.

**Comment by kdonavin** [comment]
I have this same issue. 

```
* installing *source* package ‘ps’ ...
** package ‘ps’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
/usr/local/opt/llvm/bin/clang -fopenmp  -g -O3 -Wall -pedantic -std=gnu99 -mtune=native -pipe -Wall px.c -o px
ld: library not found for -lomp
clang-8: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [px] Error 1
ERROR: compilation failed for package ‘ps’
* removing ‘/usr/local/lib/R/3.6/site-library/ps’
```

Here are my R version settings:
```
platform          x86_64-apple-darwin18.6.0
arch                                 x86_64
os                             darwin18.6.0
system                 x86_64, darwin18.6.0
status                                     
major                                     3
minor                                   6.1
year                                   2019
month                                    07
day                                      05
svn rev                               76782
language                                  R
version.string R version 3.6.1 (2019-07-05)
nickname                 Action of the Toes
```

I am not able to install clang4 from the link provided above. I run this at the root directory:

```
sudo curl -O http://r.research.att.com/libs/clang-4.0.0-darwin15.6-Release.tar.gz 
sudo tar fvxz clang-4.0.0-darwin15.6-Release.tar.gz -C /
```

That errors because `tar: Unrecognized archive format`.

Any other suggestions? Are there any others who have these issues?

**Comment by gaborcsardi** [comment]
This is not a ps error I think. ps does not set `-fopenmp`. It either a bug in the CRAN R build, defaulting to `-fopenmp`, or your custom compiler setup.

**Comment by javadba** [comment]
I have the same issue.    afaik I do not have any custom compiler setup.  If it is a bug in the CRAN R build what would be the next step?

**Comment by gaborcsardi** [comment]
@javadba how did you install R?

**Comment by javadba** [comment]
`brew install R`

I had been using it for some time . I am trying to install a github repo for respiratory ailments `repr` and it requires `devtools`

**Comment by gaborcsardi** [comment]
`/usr/local/opt/llvm/bin/clang` does not seem like the proper macOS compiler to me. 

Try finding R's `Makeconf` file, and (temporarily?) remove the `-fopenmp` flags? I don't know, I am not sure how brew R is set up. I suggest you install R from CRAN, and then you get binary packages, and don't even need to compile ps.

**Comment by javadba** [comment]
Removing the `fopenmp` flag makes sense and it may be associated with the `brew install`. That is only true in the case that compiling from source were to be required.

If the binaries were available on CRAN for given R version and target platform - then would it not be immaterial whether the  R were installed via `brew` or CRAN?

In any case i will look for the `MakeConf`  . I'm new to the `R` packaging and ecosystem but will ask my pal google on it.

**Comment by gaborcsardi** [comment]
> If the binaries were available on CRAN for given R version and target platform - then would it not be immaterial whether the R were installed via brew or CRAN?

The binary packages only work with the CRAN build of R. If you use the homebrew build, you'll have to install everything from source. E.g. the stringi package (needed by devtools) takes about 4 minutes to compile, and its binary takes 5s to intall.

**Comment by javadba** [comment]
oh wow. no idea that were the case.  ok it's time to dump brew

**Comment by gaborcsardi** [comment]
Brew is fine for everything else, though. Also `brew cask install r` installs the CRAN version, as I understand, but I have never tried...

**Comment by javadba** [comment]
well _that's_ quite a different outcome:

```
> install.packages('ps')
trying URL 'https://cloud.r-project.org/bin/macosx/el-capitan/contrib/3.6/ps_1.3.2.tgz'
Content type 'application/x-gzip' length 208566 bytes (203 KB)
==================================================
downloaded 203 KB


The downloaded binary packages are in
	/var/folders/d6/m67jyndd7h754m3810cl3bpm0000gp/T//Rtmpidu7Zl/downloaded_packages
```

Thx for helping me out on this.
