### ISSUE TITLE
New ps_cpu_count fails on non-x86 Linux

### ISSUE THREAD

**Issue by QuLogic** [r-lib/ps#60]
The new `ps_cpu_count` returns 0 on non-x86 systems ([aarch64](https://koji.fedoraproject.org/koji/taskinfo?taskID=32978623), [armv7hl](https://koji.fedoraproject.org/koji/taskinfo?taskID=32978626), [ppc64le](https://koji.fedoraproject.org/koji/taskinfo?taskID=32978622), and [s390x](https://koji.fedoraproject.org/koji/taskinfo?taskID=32978625)), causing the test to fail (as it expects non-zero result):
```
  == Failed ======================================================================
  -- 1. Failure: ps_cpu_count (@test-system.R#65)  -------------------------------
  phy > 0 isn't true.
```
It appears that `/proc/cpuinfo` is not too reliable. I don't have direct access to all these systems, but I can check ppc64le, which looks like this:
```
processor	: 0
cpu		: POWER8 (architected), altivec supported
clock		: 3425.000000MHz
revision	: 2.1 (pvr 004b 0201)

... other processors ...

timebase	: 512000000
platform	: pSeries
model		: IBM pSeries (emulated by qemu)
machine		: CHRP IBM pSeries (emulated by qemu)
MMU		: Hash
```
and armv7l, which looks like:
```
processor	: 0
model name	: ARMv7 Processor rev 0 (v7l)
BogoMIPS	: 2174.97
Features	: half thumb fastmult vfp edsp thumbee neon vfpv3 tls vfpd32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x3
CPU part	: 0xc09
CPU revision	: 0

... other processors ...

Hardware	: Highbank
Revision	: 0000
Serial		: 01234567890123456789
```

**Comment by QuLogic** [comment]
Looking around SO, the most consistent thing might be the output of `lscpu -p` (on x86_64):
```
$ lscpu -p
# The following is the parsable format, which can be fed to other
# programs. Each different item in every column has an unique ID
# starting from zero.
# CPU,Core,Socket,Node,,L1d,L1i,L2,L3
0,0,0,0,,0,0,0,0
1,1,0,0,,1,1,1,0
2,2,0,0,,2,2,2,0
3,3,0,0,,3,3,3,0
```
The cache information is not always there, but on the systems I could check, CPU/Core/Socket were always available, e.g., ppc64le:
```
# The following is the parsable format, which can be fed to other
# programs. Each different item in every column has an unique ID
# starting from zero.
# CPU,Core,Socket,Node,,L1d,L1i
0,0,0,0,,0,0
1,1,1,0,,1,1
```
or armv7l:
```
# The following is the parsable format, which can be fed to other
# programs. Each different item in every column has an unique ID
# starting from zero.
# CPU,Core,Socket,Node
0,0,0,
1,1,0,
2,2,0,
3,3,0,
```

**Comment by gaborcsardi** [comment]
Thanks! The problem is, I cannot test on these architectures. Nevertheless I'll change the code, so the it'll return `NA` instead of zero. I'll update the test case as well.

As for detecting the correct value, please feel free to submit a PR. Thanks!
