### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by mike-molnar** [r-lib/ps#66]
Hi,

I'm trying to install ps with R version 3.6.0, but I get an error with the code.  I tried to install using R version 3.5.3 and recieved the same error:

* installing *source* package ‘ps’ ...
** package ‘ps’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
gcc -std=gnu99 -O3 -std=c99 -Wall px.c -o px
px.c: In function ‘main’:
px.c:119:7: warning: implicit declaration of function ‘usleep’ [-Wimplicit-function-declaration]
       if (fnum > 0) usleep((useconds_t) (fnum * 1000.0 * 1000.0));
       ^
px.c:119:29: error: ‘useconds_t’ undeclared (first use in this function)
       if (fnum > 0) usleep((useconds_t) (fnum * 1000.0 * 1000.0));
                             ^
px.c:119:29: note: each undeclared identifier is reported only once for each function it appears in
Makevars:11: recipe for target 'px' failed
make: *** [px] Error 1
ERROR: compilation failed for package ‘ps’

Any help would be appreciated.

Best,

**Comment by gaborcsardi** [comment]
We can't help you if you don't tell us anything about the ps version you are trying to install and your platform.

**Comment by mike-molnar** [comment]
Sorry about that.  Here is that information:
ps version: 1.3.0
R version 3.6.0 (2019-04-26)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 8 (jessie)

**Comment by gaborcsardi** [comment]
Thanks, can you pls try the version on GitHub?

**Comment by gaborcsardi** [comment]
I am closing. Please reopen if you have problems.
