### ISSUE TITLE
Unable to install ps on dockerized R 3.6

### ISSUE THREAD

**Issue by rbreunev** [r-lib/ps#78]
Hello :) 

Here are the versions and platform informations : 

_ps version: 1.3.2
R version : 3.6.0 (2019-04-26)
Docker version : 18.06.3-ce
Platform : linux/amd64
Running under: Alpine Linux v3.11.2_

Here is the error I have during docker build : 

```
posix.c:39:10: fatal error: linux/types.h: No such file or directory
   39 | #include <linux/types.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make: *** [/usr/lib/R/etc/Makeconf:167: posix.o] Error 1
ERROR: compilation failed for package ‘ps’
* removing ‘/usr/local/lib/R/site-library/ps’ 
```

Other installation issues do not correspond at 100% : 

#66 : no solution provided (same R version)
#55, #52 : same error but not same OS
#63 : not the same error (same R version) 

Any help would be appreciated.

Regards.

**Comment by gaborcsardi** [comment]
Sorry, closed accidentally. On ALpine you need to install the `linux-headers` package:

```r
apk add linux-headers
```

**Comment by rbreunev** [comment]
Thanks a lot 👍 . 
It did the job.
