### ISSUE TITLE
lsof on Windows

### ISSUE THREAD

**Issue by krlmlr** [r-lib/ps#79]
For https://github.com/r-lib/remotes/issues/368.

Since we don't care about portability for this particular problem, we could use a Windows-only approach as discussed [in that CodeGuru post](https://www.codeguru.com/cpp/w-p/system/processesmodules/article.php/c2827/Examine-Information-on-Windows-NT-System-Level-Primitives.htm), found via https://stackoverflow.com/q/183925/946850.

**Comment by gaborcsardi** [comment]
I tried the `WhoUses` tool from the CodeGuru post, but it does not work for me. It has a `/M` switch for dlls specifically but it gives me 
```
SystemModulesInformation::Refresh() failed.
```
