### ISSUE TITLE
Can't build on R 3.6.0

### ISSUE THREAD

**Issue by pascalgulikers** [r-lib/ps#84]
Trying to build ps 1.3.3 on various R versions. R_3.5.1_x86_64-redhat-linux-gnu and R_3.5.2_x86_64-redhat-linux-gnu succeed, but R_3.6.0_x86_64-redhat-linux-gnu not.

* installing *source* package ‘ps’ ...
** using staged installation
ERROR: 'configure' exists but is not executable -- see the 'R Installation and Administration Manual'

```r
# insert reprex here
```

**Comment by gaborcsardi** [comment]
How are you installing it?

**Comment by pascalgulikers** [comment]
install.packages(pack, lib = installPath, repos = repos, destdir = pkg_path, INSTALL_opts = c("--build", "--no-multiarch"), method = "wget")

**Comment by gaborcsardi** [comment]
I have no clue what this is, the `configure` file is definitely executable. You can see it if you clone https://github.com/cran/ps or r-lib/ps. Is it possible that your untar removes the executable bit.

**Comment by pascalgulikers** [comment]
Really weird, I can only install it under root access

**Comment by gaborcsardi** [comment]
Maybe a disk partition is mounted noexec? I.e. no executable files are allowed on it?

**Comment by gaborcsardi** [comment]
Possibly `/tmp`? Try to run `mount` and if you can set `TMPDIR` to a place that allows executables.

You can also try a non-staged installation, that probably does not use `/tmp`.

In any case, I don't think this is a bug with ps, so I will close this issue.

**Comment by pascalgulikers** [comment]
Compiling works on 3.5.x but not on 3.6.x. Using the same install options.

**Comment by gaborcsardi** [comment]
I think 3.5 does not have staged installation, so it does not use the temporary directory. Hence my suggested workarounds.

**Comment by pascalgulikers** [comment]
It seems that the temp path of one of our servers didn't have the right permissions set for the temp path. Sorry to have bothered you!

**Comment by gaborcsardi** [comment]
No problem, great you worked it out.
