### ISSUE TITLE
Cannot update from v1.3.4 to v1.4.0

### ISSUE THREAD

**Issue by RobPastoor** [r-lib/ps#97]
Got this error:

> install.packages("ps")

  There is a binary version available but the source version is later:
   binary source needs_compilation
ps  1.3.4  1.4.0              TRUE

installing the source package ‘ps’

trying URL 'https://cran.rstudio.com/src/contrib/ps_1.4.0.tar.gz'
Content type 'application/x-gzip' length 110708 bytes (108 KB)
downloaded 108 KB

* installing *source* package 'ps' ...
** package 'ps' successfully unpacked and MD5 sums checked
** using staged installation
./configure: line 78: D:/Program: No such file or directory
./configure: line 81: D:/Program: No such file or directory
./configure: line 150: D:/Program: No such file or directory
** libs
"D:/Program Files/rtools40/mingw64/bin/"gcc  -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign -Wall px.c -o px
D:/Program Files/rtools40/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find D:/Program: No such file or directory
D:/Program Files/rtools40/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find Files/rtools40/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/lib/../lib/default-manifest.o: No such file or directory
collect2.exe: error: ld returned 1 exit status
make: *** [Makevars:11: px] Error 1
ERROR: compilation failed for package 'ps'
* removing 'D:/Program Files/R/R-4.0.2/library/ps'
* restoring previous 'D:/Program Files/R/R-4.0.2/library/ps'
Warning in install.packages :
  installation of package ‘ps’ had non-zero exit status

The downloaded source packages are in
	‘C:\Users\robpa\AppData\Local\Temp\RtmpSwWXtm\downloaded_packages’
Making 'packages.html' ... done

**Comment by gaborcsardi** [comment]
I can fix these:
```
./configure: line 78: D:/Program: No such file or directory
./configure: line 81: D:/Program: No such file or directory
./configure: line 150: D:/Program: No such file or directory
```
But I don't think I can fix the rest, because it is coming from base R. R is not very good with spaces in path names, especially if they are not on the `c:` drive.

You can wait for the binary package to appear, or install ps from here:
```
install.packages("ps", repos = "https://packagemanager.rstudio.com/all/latest")
```

**Comment by RobPastoor** [comment]
Hi Gábor,

You solution [ _install.packages("ps", repos = "https://packagemanager.rstudio.com/all/latest")_ ] is working, but it installs v1.3.4...

Kind regards,

Rob Pastoor.

> install.packages("ps", repos = "https://packagemanager.rstudio.com/all/latest")
trying URL 'https://packagemanager.rstudio.com/all/latest/bin/windows/contrib/4.0/ps_1.3.4.zip'
Content type 'binary/octet-stream' length 738617 bytes (721 KB)
downloaded 721 KB

package ‘ps’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\robpa\AppData\Local\Temp\RtmpWmDgtl\downloaded_packages

**Comment by gaborcsardi** [comment]
Seems like there is an 1.4.0 binary now: https://cran.rstudio.com/web/packages/ps/
So you can try again.

**Comment by RobPastoor** [comment]
Hi Gábor,

YES! It is working now.
I can update the package using the update function in RStudio.

Thanks, for helping out!

Have a good weekend, and stay safe.

Rob Pastoor.
